# .github/workflows/deploy.yml
name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_FRONTEND: ${{ secrets.AZURE_WEBAPP_NAME_FRONTEND }}
  AZURE_WEBAPP_NAME_BACKEND: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
  AZURE_WEBAPP_PACKAGE_PATH_FRONTEND: './frontend'
  AZURE_WEBAPP_PACKAGE_PATH_BACKEND: './backend'
  NODE_VERSION: '18.x'

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}/package-lock.json

    - name: npm install and build
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}
        npm install
        npm run build --if-present

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_FRONTEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_FRONTEND }}/build

  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}/package-lock.json

    - name: npm install
      run: |
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}
        npm install

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_BACKEND }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH_BACKEND }}